// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPI_Items.DatabaseContext;

#nullable disable

namespace RestAPI_Items.Migrations
{
    [DbContext(typeof(ItemDatabaseContext))]
    partial class ItemDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("RestAPI_Items.Models.ItemModel", b =>
                {
                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<char?>("ItemFabric")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ItemPrice")
                        .HasColumnType("REAL");

                    b.Property<bool>("ItemWillRestock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemName");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
